version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pick-perfume-app
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pick_perfume?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-dev}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-dev_password}
      - ELASTICSEARCH_HOST=http://elasticsearch
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    restart: always

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: pick-perfume-opensearch
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin1234
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./user_dict.txt:/usr/share/elasticsearch/config/user_dict.txt
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      bash -c "
        if ! /usr/share/opensearch/bin/opensearch-plugin list | grep -q analysis-nori; then
          /usr/share/opensearch/bin/opensearch-plugin install analysis-nori;
        fi && 
        /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    networks:
      - app-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: pick-perfume-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: pick_perfume
      MYSQL_USER: ${DB_USERNAME:-dev}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dev_password}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:
  es-data:

networks:
  app-network:
    driver: bridge
