version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pick-perfume-mysql
    ports:
      - "3396:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pick_perfume
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  mysql-data: