version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: pick-perfume-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./src/main/resources/es-settings.json:/usr/share/elasticsearch/config/es-settings.json
      - ./src/main/resources/analysis:/usr/share/elasticsearch/config/analysis
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      bash -c "
        elasticsearch-plugin install analysis-nori --batch || true &&
        /usr/local/bin/docker-entrypoint.sh elasticsearch"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: pick-perfume-mysql
    ports:
      - "3396:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pick_perfume
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  mysql-data:
  es-data:

networks:
  app-network:
    driver: bridge
