spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3396/pick_perfume?&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
    timeout: 3600 # 세션 타임아웃 (초)
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: ${ELASTICSEARCH_CONNECTION_TIMEOUT:5s}
    socket-timeout: ${ELASTICSEARCH_SOCKET_TIMEOUT:30s}
  batch:
    jdbc:
      initialize-schema: always

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

aws:
  access-key: ${AWS_ACCESS_KEY:}
  secret-key: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:}

app:
  session:
    cookie:
      secure: true # HTTPS에서만 쿠키 전송
      same-site: Lax # SameSite 설정
      domain: ${APP_DOMAIN:} # 쿠키 도메인 (환경변수에서 가져옴)
    max-sessions-per-user: 1 # 사용자당 최대 세션 수
    expire-oldest-session: true # 최대 세션 수 초과 시 가장 오래된 세션 만료
    cleanup-cron: 0 0 */1 * * * # 만료된 세션 정리 주기 (1시간마다)

server:
  servlet:
    session:
      cookie:
        same-site: lax
