spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3396/pick_perfume?&serverTimezone=UTC
    username: dev
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        allow_update_outside_transaction: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  elasticsearch:
    uris: http://${elasticsearch.host:localhost}:${elasticsearch.port:9200}
    connection-timeout: 1s
    socket-timeout: 30s
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
