spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3396/pick_perfume?&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
    timeout: 3600 # 세션 타임아웃 (초)
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: ${ELASTICSEARCH_CONNECTION_TIMEOUT:5s}
    socket-timeout: ${ELASTICSEARCH_SOCKET_TIMEOUT:30s}
  batch:
    jdbc:
      initialize-schema: never



springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID:}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/callback/kakao}
    client-secret: ${KAKAO_CLIENT_SECRET:}

app:
  domainUrl: ${APP_DOMAIN_URL:http://localhost:3000}
  session:
    cookie:
      secure: true
      same-site: Lax
      domain: ${APP_DOMAIN:}
    max-sessions-per-user: 1
    expire-oldest-session: true
    cleanup-cron: 0 0 */1 * * *

server:
  servlet:
    session:
      cookie:
        same-site: lax

cloudflare:
  r2:
    account:
      id: ${CLOUDFLARE_R2_ACCOUNT_ID:}
    access:
      key: ${CLOUDFLARE_R2_ACCESS_KEY_ID:}
      secret: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY:}
    bucket:
      name: ${CLOUDFLARE_R2_BUCKET_NAME:scentist}
    public:
      url: ${CLOUDFLARE_R2_PUBLIC_URL:}

