ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT
    DROP FOREIGN KEY JOB_EXEC_CTX_FK;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    DROP FOREIGN KEY JOB_EXEC_PARAMS_FK;

ALTER TABLE BATCH_STEP_EXECUTION
    DROP FOREIGN KEY JOB_EXEC_STEP_FK;

ALTER TABLE BATCH_JOB_EXECUTION
    DROP FOREIGN KEY JOB_INST_EXEC_FK;

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT
    DROP FOREIGN KEY STEP_EXEC_CTX_FK;

ALTER TABLE survey
    ADD session_id VARCHAR(255) NULL;

DROP TABLE BATCH_JOB_EXECUTION;

DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;

DROP TABLE BATCH_JOB_EXECUTION_PARAMS;

DROP TABLE BATCH_JOB_EXECUTION_SEQ;

DROP TABLE BATCH_JOB_INSTANCE;

DROP TABLE BATCH_JOB_SEQ;

DROP TABLE BATCH_STEP_EXECUTION;

DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;

DROP TABLE BATCH_STEP_EXECUTION_SEQ;