name: Deploy to AWS Elastic Beanstalk (Java Platform)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp -r .ebextensions deploy/
          cp -r .platform deploy/
          jarfile=$(find build -name "*.jar" -not -path "*/tmp/*" | head -n 1)
          if [ -z "$jarfile" ]; then
            echo "JAR 파일을 찾을 수 없습니다."
            exit 1
          fi
          echo "Found JAR file: $jarfile"
          mkdir -p deploy/build/libs
          cp "$jarfile" deploy/build/libs/
          cp Procfile deploy/
          cp mapping.json settings.json deploy/
          cd deploy && zip -r ../deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: java-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300
          use_existing_version_if_available: true
